name: End to end integration tests

on:
  pull_request:
    # see https://github.com/codethread/pomo-electron/issues/19
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.9.1'
      - name: Install dependencies
        run: yarn install
      - name: Setup machines
        run: yarn machine
      - name: Build bundle
        run: yarn build
      # - name: Install Playwright
      #   run: npx playwright install --with-deps
      - name: Run your tests
        run: yarn e2e
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: playwright-results
          path: test-results
# name: End to end integration tests

# on:
#   pull_request:
#     # see https://github.com/codethread/pomo-electron/issues/19
#     branches: [never]

# jobs:
#   docker:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v1
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1
#       - name: Build and push
#         id: docker_build
#         uses: docker/build-push-action@v2
#         with:
#           push: false
#           tags: user/app:latest
